/* Generated by tools/build.py from Song Sets.xlsx and the Choruses folders. Do not edit by hand. */
window.PG = {
 "CRYPTO": {
  "salt": "2f3c706ea3d0a0f89fe3e2b6f39d0289",
  "iter": 250000,
  "check": "b11efebadf8f2ab22020f3d3c0488d7a5567501adece4ca71475181acf13480aa598db4d43f16235d441121b9125"
 },
 "SONGS": [
  {
   "id": "a-thousand-hallelujahs",
   "en": "A Thousand Hallelujahs",
   "zh": "千声哈利路亚",
   "key": "Db",
   "ccli": 7190270,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "all-creatures-of-our-god-and-king-lasst-uns-erfreuen",
   "en": "All Creatures of Our God and King",
   "zh": "主手所造",
   "key": "D",
   "ccli": 1503,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "all-glory-be-to-christ",
   "en": "All Glory Be to Christ",
   "zh": "荣耀归于基督",
   "key": "E",
   "ccli": 7008232,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "all-i-have-is-christ",
   "en": "All I Have Is Christ",
   "zh": "基督我所有",
   "key": "D",
   "ccli": 5174122,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "amazing-grace",
   "en": "Amazing Grace",
   "zh": "奇异恩典",
   "key": "G",
   "ccli": 22025,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "be-thou-my-vision",
   "en": "Be Thou My Vision",
   "zh": "成为我异象",
   "key": "D",
   "ccli": 7056332,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "before-the-throne-of-god-above",
   "en": "Before the Throne of God Above",
   "zh": "在高天真神宝座前",
   "key": "D",
   "ccli": 2306412,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "behold-our-god",
   "en": "Behold Our God",
   "zh": "",
   "key": "C",
   "ccli": 5937510,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "build-my-life",
   "en": "Build My Life",
   "zh": "",
   "key": "G",
   "ccli": 7070345,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "christ-our-hope-in-life-and-death",
   "en": "Christ Our Hope in Life and Death",
   "zh": "生死盼望在基督",
   "key": "F",
   "ccli": 7147502,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "christus-victor-amen",
   "en": "Christus Victor (Amen)",
   "zh": "基督得胜者",
   "key": "F",
   "ccli": 7245980,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "come-praise-and-glorify",
   "en": "Come Praise and Glorify",
   "zh": "来赞美我们的上帝",
   "key": "A",
   "ccli": 6167664,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "facing-a-task-unfinished-we-go-to-all-the-world",
   "en": "Facing a Task Unfinished",
   "zh": "工尚未成",
   "key": "C",
   "ccli": 7002026,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "great-is-thy-faithfulness",
   "en": "Great Is Thy Faithfulness",
   "zh": "你的信实广大",
   "key": "D",
   "ccli": 18723,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "he-will-hold-me-fast",
   "en": "He Will Hold Me Fast",
   "zh": "主必保守我",
   "key": "G",
   "ccli": 7016161,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "here-we-stand",
   "en": "Here We Stand",
   "zh": "我们在这蒙赎的教会",
   "key": "D",
   "ccli": 7201507,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "his-mercy-is-more",
   "en": "His Mercy Is More",
   "zh": "祂怜悯更多",
   "key": "G",
   "ccli": 7065053,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "holy-holy-holy-nicaea",
   "en": "Holy, Holy, Holy",
   "zh": "圣哉，圣哉，圣哉",
   "key": "D",
   "ccli": 1156,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "how-deep-the-father-s-love-for-us",
   "en": "How Deep the Father's Love for Us",
   "zh": "天父的爱深越海洋",
   "key": "D",
   "ccli": 1558110,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "how-great-is-our-god",
   "en": "How Great Is Our God",
   "zh": "我神真伟大",
   "key": "C",
   "ccli": 4348399,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "how-great-thou-art",
   "en": "How Great Thou Art",
   "zh": "你真伟大",
   "key": "Bb",
   "ccli": 14181,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "i-know-who-holds-tomorrow",
   "en": "I Know Who Holds Tomorrow",
   "zh": "我知谁掌管明天",
   "key": "C",
   "ccli": 17982,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "immanuel",
   "en": "Immanuel",
   "zh": "以马内利",
   "key": "D",
   "ccli": 71014,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "in-christ-alone",
   "en": "In Christ Alone",
   "zh": "在基督里",
   "key": "Eb",
   "ccli": 3350395,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "it-is-well-with-my-soul",
   "en": "It Is Well with My Soul",
   "zh": "我心灵得安宁",
   "key": "C",
   "ccli": 25376,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "jerusalem",
   "en": "Jerusalem",
   "zh": "耶路撒冷",
   "key": "B",
   "ccli": 7003218,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "jesus-paid-it-all-christ-i-owe",
   "en": "Jesus Paid It All",
   "zh": "主为我舍身",
   "key": "Db",
   "ccli": 22331,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "jesus-strong-and-kind",
   "en": "Jesus, Strong and Kind",
   "zh": "良善全能主",
   "key": "C",
   "ccli": 7139992,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "joy-to-the-world-antioch",
   "en": "Joy to the World",
   "zh": "普世欢腾",
   "key": "D",
   "ccli": 24016,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "no-other-name-hillsong",
   "en": "No Other Name (Hillsong)",
   "zh": "别无他名",
   "key": "G",
   "ccli": 7019979,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "no-other-name-trevor-hodge",
   "en": "No Other Name (Trevor Hodge)",
   "zh": "别无他名",
   "key": "Bb",
   "ccli": 5737284,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "o-breath-of-life",
   "en": "O Breath of Life",
   "zh": "生命的灵",
   "key": "B",
   "ccli": 5439290,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "o-come-all-ye-faithful-adeste-fideles",
   "en": "O Come, All Ye Faithful",
   "zh": "齐来，宗主信徒",
   "key": "G",
   "ccli": 31054,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "o-great-god",
   "en": "O Great God",
   "zh": "哦伟大至高神",
   "key": "C",
   "ccli": 4804015,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "only-a-holy-god",
   "en": "Only a Holy God",
   "zh": "圣洁的神",
   "key": "D",
   "ccli": 7073332,
   "pages": 4,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "rock-of-ages-toplady",
   "en": "Rock of Ages",
   "zh": "万古磐石为我开",
   "key": "Bb",
   "ccli": 40588,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "the-power-of-the-cross",
   "en": "The Power of the Cross",
   "zh": "十字架的大能",
   "key": "A",
   "ccli": 4490766,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "turn-your-eyes-upon-jesus",
   "en": "Turn Your Eyes Upon Jesus",
   "zh": "当转眼仰望耶稣",
   "key": "F",
   "ccli": 15960,
   "pages": 1,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "we-are-one-in-the-father-s-love",
   "en": "We Are One (In the Father's Love)",
   "zh": "合而为一",
   "key": "Bb",
   "ccli": 7145090,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "when-i-survey",
   "en": "When I Survey",
   "zh": "奇妙十架",
   "key": "Eb",
   "ccli": 7273855,
   "pages": 3,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "yet-not-i-but-through-christ-in-me",
   "en": "Yet Not I but Through Christ in Me",
   "zh": "不是我 是基督住我心",
   "key": "C",
   "ccli": 7121852,
   "pages": 2,
   "lib": "en",
   "sheet": true
  },
  {
   "id": "hark-the-herald-angels-sing-mendelssohn",
   "en": "Hark! The Herald Angels Sing",
   "zh": "听那天使高声唱",
   "key": "F",
   "ccli": 27738,
   "pages": 1,
   "lib": "zh",
   "sheet": true
  },
  {
   "id": "o-holy-night",
   "en": "O Holy Night",
   "zh": "哦圣善夜",
   "key": "C",
   "ccli": 32015,
   "pages": 2,
   "lib": "zh",
   "sheet": true
  }
 ],
 "SCHEDULE": [
  {
   "d": "2026-08-30",
   "type": "Parallel",
   "passage": "Revelation 7:9–17",
   "mEn": "Lucy, Enya",
   "en": [
    "holy-holy-holy-nicaea",
    "a-thousand-hallelujahs",
    "all-glory-be-to-christ"
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-09-06",
   "type": "Combined · Father's Day",
   "passage": "Matthew 22:1–14",
   "mEn": "Enya, Jenny",
   "en": [
    "great-is-thy-faithfulness",
    "only-a-holy-god",
    "how-deep-the-father-s-love-for-us"
   ],
   "mCn": "",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-09-13",
   "type": "Combined · Communion",
   "passage": "Galatians 3:27–4:7",
   "mEn": "Lucy, Chelsea",
   "en": [
    "build-my-life",
    "christ-our-hope-in-life-and-death",
    "a-thousand-hallelujahs"
   ],
   "mCn": "",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-09-20",
   "type": "Parallel",
   "passage": "Luke 1:1–25",
   "mEn": "Elim, Enya",
   "en": [
    "great-is-thy-faithfulness",
    "all-i-have-is-christ",
    "jesus-strong-and-kind"
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-09-27",
   "type": "Parallel · Mid-Autumn Festival",
   "passage": "John 8:12–20; Matthew 5:14–16",
   "mEn": "David, Jenny",
   "en": [
    "a-thousand-hallelujahs",
    "we-are-one-in-the-father-s-love",
    "his-mercy-is-more"
   ],
   "mCn": "Eileen Zhang, Enya (TBC)",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-10-04",
   "type": "Combined · Communion",
   "passage": "Luke 1:26–45",
   "mEn": "Lucy, Chelsea",
   "en": [
    {
     "en": "Whom Have I in Heaven But You",
     "zh": ""
    },
    "yet-not-i-but-through-christ-in-me",
    "all-i-have-is-christ"
   ],
   "mCn": "",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-10-11",
   "type": "Combined · 157th Anniversary",
   "passage": "Luke 3:1–38",
   "mEn": "Enya, Lucy, Peter Li, Jenny",
   "en": [
    "christus-victor-amen",
    "all-glory-be-to-christ",
    "facing-a-task-unfinished-we-go-to-all-the-world"
   ],
   "mCn": "",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-10-18",
   "type": "Parallel",
   "passage": "Luke 4:1–15",
   "mEn": "Elim, Enya",
   "en": [
    "all-i-have-is-christ",
    "great-is-thy-faithfulness",
    "jerusalem"
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-10-25",
   "type": "Parallel",
   "passage": "Luke 4:16–44",
   "mEn": "Lucy, Chelsea",
   "en": [
    "build-my-life",
    "only-a-holy-god",
    {
     "en": "Calling All Sinners",
     "zh": ""
    }
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-11-01",
   "type": "Combined · Communion",
   "passage": "Luke 5:1–26",
   "mEn": "Enya, Peter Li",
   "en": [
    "great-is-thy-faithfulness",
    "i-know-who-holds-tomorrow",
    "jesus-strong-and-kind"
   ],
   "mCn": "",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-11-08",
   "type": "Parallel",
   "passage": "Luke 5:27–39",
   "mEn": "Jenny, Chelsea",
   "en": [
    "here-we-stand",
    "his-mercy-is-more",
    "jesus-paid-it-all-christ-i-owe"
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-11-15",
   "type": "Parallel",
   "passage": "Luke 6:1–19",
   "mEn": "Lucy, Chelsea",
   "en": [
    "no-other-name-hillsong",
    "jerusalem",
    "all-glory-be-to-christ"
   ],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-11-22",
   "type": "Parallel · King of the Universe",
   "passage": "Luke 6:20–49",
   "mEn": "Enya, Jenny",
   "en": [],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  },
  {
   "d": "2026-11-29",
   "type": "Parallel",
   "passage": "Luke 7:1–30",
   "mEn": "Elim, Enya",
   "en": [],
   "mCn": "Eileen Zhang",
   "cn": [],
   "notes": ""
  }
 ],
 "NOSHEET": [
  {
   "id": null,
   "en": "On That Day",
   "zh": "在那日",
   "lib": "en",
   "sheet": false,
   "note": "Lead sheet to be re-downloaded"
  },
  {
   "id": null,
   "en": "Calling All Sinners",
   "zh": "",
   "lib": "en",
   "sheet": false,
   "note": "Not available on SongSelect"
  },
  {
   "id": null,
   "en": "As the Deer",
   "zh": "如鹿切慕溪水",
   "lib": "zh",
   "sheet": false,
   "note": "To be downloaded"
  },
  {
   "id": null,
   "en": "",
   "zh": "主我相信",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "我的心你要称颂耶和华",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "这一生最美的祝福",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "真光",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "坐在宝座上圣洁羔羊",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "活出爱",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "认定你",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "鸡叫的时候",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "Who Do I Have But You",
   "zh": "除你以外",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "是这份爱",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "叫我抬起头的神",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "真实的悔改",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "医治的爱",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "深触我心",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "宝贵十架",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "有一位神",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "专心仰望耶稣",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "Who Can Separate Us",
   "zh": "谁能使我与神的爱隔绝",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "我要向高山举目",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "我要一心称谢你",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "十架的爱",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "我愿为你去",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "How Could It Be",
   "zh": "何等恩典",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "爱中相遇",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "",
   "zh": "一生爱你",
   "lib": "zh",
   "sheet": false,
   "note": ""
  },
  {
   "id": null,
   "en": "Love, Joy and Life",
   "zh": "爱喜乐生命",
   "lib": "zh",
   "sheet": false,
   "note": ""
  }
 ],
 "updated": "2026-09-26"
};
